<a href="https://colab.research.google.com/github/rozadoesn-stack/ML-Basic/blob/main/homework_07/homework_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [ ]:
massiv = np.zeros(10)
massiv[4] = 1
print (massiv)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [ ]:
massiv = np.arange(10,50)
new_massiv = massiv[::-1]
a = new_massiv[new_massiv%2==0]
print(a)


[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [ ]:
massiv = np.arange(0,9)
new_massiv= massiv.reshape(3,3)
print(new_massiv)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [ ]:
rng = np.random.default_rng()
massiv = rng.random((4, 3, 2))
min_value = massiv.min()
max_value = massiv.max()
print (massiv)
print("Минимум:", min_value)
print("Максимум:", max_value)




[[[0.6642125  0.20342216]
  [0.53199298 0.55765408]
  [0.96253    0.14371746]]

 [[0.62235666 0.10393195]
  [0.51812575 0.77417402]
  [0.52791034 0.94909824]]

 [[0.48847026 0.76132075]
  [0.08220969 0.395859  ]
  [0.74680508 0.1089984 ]]

 [[0.40834703 0.69358063]
  [0.63974553 0.47661044]
  [0.44175475 0.22687935]]]
Минимум: 0.08220969183283633
Максимум: 0.9625300031067836


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение.

In [ ]:
rng = np.random.default_rng()
a = rng.integers(low=1, high=15, size=(6,4))
b = rng.integers(low=1, high=15, size=(4,3))
c = a@b
print("Массив a:\n", a)
print("\nМассив b:\n", b)
print("\nМассив c:\n", c)


Массив a:
 [[13  1  8  6]
 [11  5  9  4]
 [10 13  1 13]
 [12 13  6 11]
 [ 7  9 14  1]
 [ 3  9 14  4]]

Массив b:
 [[ 3  4  3]
 [13 11  8]
 [ 3 12  9]
 [13 13  6]]

Массив c:
 [[154 237 155]
 [177 259 178]
 [371 364 221]
 [366 406 260]
 [193 308 225]
 [220 331 231]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [21]:
rng = np.random.default_rng()
massiv = rng.integers(0, 101, size=(7, 7))
new_massiv = (massiv-np.mean(massiv))/np.std(massiv)
print (massiv)
print (f'Среднее отклонение:{np.mean(massiv):.2f}')
print (f'Страндартное отклонение:{np.std(massiv):.2f}')
print("\nНормализованный массив (округленный):")
print (new_massiv.round(2))


[[ 19  45  85  29  65  53   9]
 [ 44  21  60  14  54  11   2]
 [ 37  76  48  36  27  73   6]
 [  3  94  22  99  40  55  17]
 [  4  37  53  23  39  91  57]
 [ 97   6  46  32  55  57 100]
 [ 16   4  11  88  31  40  37]]
Среднее отклонение:42.20
Страндартное отклонение:28.24

Нормализованный массив (округленный):
[[-0.82  0.1   1.52 -0.47  0.81  0.38 -1.18]
 [ 0.06 -0.75  0.63 -1.    0.42 -1.1  -1.42]
 [-0.18  1.2   0.21 -0.22 -0.54  1.09 -1.28]
 [-1.39  1.83 -0.72  2.01 -0.08  0.45 -0.89]
 [-1.35 -0.18  0.38 -0.68 -0.11  1.73  0.52]
 [ 1.94 -1.28  0.13 -0.36  0.45  0.52  2.05]
 [-0.93 -1.35 -1.1   1.62 -0.4  -0.08 -0.18]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ